"""
Karenina serve and init commands - CLI for webapp server and configuration setup.

This module provides commands to:
- Initialize a Karenina workspace with configuration and directories
- Start the webapp server (requires karenina[webapp] to be installed)
"""

import json
import os
from pathlib import Path
from typing import Any

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table

console = Console()

# Server defaults
DEFAULT_PORT = 8080

# Default configuration values
DEFAULTS: dict[str, Any] = {
    "provider": "openai",
    "model": "gpt-4.1-mini",
    "interface": "langchain",
    "async_enabled": True,
    "async_max_workers": 2,
}

MODEL_DEFAULTS: dict[str, str] = {
    "openai": "gpt-4.1-mini",
    "anthropic": "claude-haiku-4-5",
    "google_genai": "gemini-pro",
    "openrouter": "openai/gpt-4o-mini",
}


def _ensure_directory(path: Path) -> bool:
    """Create directory if it doesn't exist. Returns True if created."""
    if not path.exists():
        path.mkdir(parents=True)
        return True
    return False


def _get_default_dirs(working_dir: Path) -> dict[str, Path]:
    """Return the standard directory layout for a Karenina workspace."""
    return {
        "db_path": working_dir / "dbs",
        "presets_dir": working_dir / "presets",
        "mcp_presets_dir": working_dir / "mcp_presets",
        "checkpoints_dir": working_dir / "checkpoints",
    }


def _create_directories(dirs: dict[str, Path], *, verbose: bool = False) -> None:
    """Create workspace directories, optionally printing status for each."""
    for dir_name, path in dirs.items():
        created = _ensure_directory(path)
        if verbose:
            status = "[green]created[/green]" if created else "[dim]exists[/dim]"
            console.print(f"  {dir_name}: {path} ({status})")
        else:
            console.print(f"  [green]✓[/green] {dir_name}: {path}")


def _write_defaults_json(working_dir: Path, provider: str, model: str) -> None:
    """Write defaults.json configuration file."""
    defaults_file = working_dir / "defaults.json"
    defaults_config = {
        "default_interface": DEFAULTS["interface"],
        "default_provider": provider,
        "default_model": model,
        "default_endpoint_base_url": "",
    }
    defaults_file.write_text(json.dumps(defaults_config, indent=2))


def _write_env_file(
    working_dir: Path,
    dirs: dict[str, Path],
    *,
    async_enabled: bool,
    async_workers: int,
    api_keys: dict[str, str] | None = None,
    header_comment: str = "generated by karenina init",
) -> None:
    """Write .env file with directory paths, async settings, and API key placeholders."""
    env_file = working_dir / ".env"
    env_lines = [
        f"# Karenina Configuration ({header_comment})",
        f"DB_PATH={dirs['db_path']}",
        f"KARENINA_PRESETS_DIR={dirs['presets_dir']}",
        f"MCP_PRESETS_DIR={dirs['mcp_presets_dir']}",
        f"KARENINA_ASYNC_ENABLED={str(async_enabled).lower()}",
        f"KARENINA_ASYNC_MAX_WORKERS={async_workers}",
        "",
        "# API Keys",
    ]
    if api_keys:
        for key, value in api_keys.items():
            env_lines.append(f"{key}={value}")
    for key in ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GOOGLE_API_KEY"]:
        if not api_keys or key not in api_keys:
            env_lines.append(f"# {key}=")

    env_file.write_text("\n".join(env_lines) + "\n")
    os.chmod(env_file, 0o600)


def run_default_setup(working_dir: Path) -> dict[str, Path]:
    """Quick setup with sensible defaults. Shows what was configured."""
    console.print("\n[bold blue]Karenina Quick Setup[/bold blue]\n")
    console.print("[dim]Using default configuration. Run 'karenina init --advanced' for custom setup.[/dim]\n")

    dirs = _get_default_dirs(working_dir)
    _create_directories(dirs, verbose=True)
    _write_defaults_json(working_dir, provider=str(DEFAULTS["provider"]), model=str(DEFAULTS["model"]))
    _write_env_file(
        working_dir,
        dirs,
        async_enabled=bool(DEFAULTS["async_enabled"]),
        async_workers=int(DEFAULTS["async_max_workers"]),
    )

    # Show summary
    console.print("\n[bold]Configuration Summary:[/bold]")
    table = Table(show_header=False, box=None)
    table.add_column("Setting", style="cyan")
    table.add_column("Value")
    table.add_row("Default Provider", str(DEFAULTS["provider"]))
    table.add_row("Default Model", str(DEFAULTS["model"]))
    table.add_row("Async Workers", str(DEFAULTS["async_max_workers"]))
    console.print(table)

    console.print("\n[yellow]Note:[/yellow] Add your API keys to .env before using LLM features.")
    console.print("[bold green]Setup complete![/bold green]\n")
    return dirs


def run_advanced_setup(working_dir: Path) -> dict[str, Path]:
    """Full guided setup with all configuration options."""
    console.print("\n[bold blue]Karenina Advanced Setup[/bold blue]\n")

    # Directory configuration
    console.print("[bold]1. Directory Configuration[/bold]")
    dirs: dict[str, Path] = {}

    dirs["db_path"] = Path(
        Prompt.ask(
            "Database directory",
            default=str(working_dir / "dbs"),
        )
    )
    dirs["presets_dir"] = Path(
        Prompt.ask(
            "Presets directory",
            default=str(working_dir / "presets"),
        )
    )
    dirs["mcp_presets_dir"] = Path(
        Prompt.ask(
            "MCP presets directory",
            default=str(working_dir / "mcp_presets"),
        )
    )
    dirs["checkpoints_dir"] = Path(
        Prompt.ask(
            "Checkpoints directory",
            default=str(working_dir / "checkpoints"),
        )
    )

    _create_directories(dirs)

    # LLM Configuration
    console.print("\n[bold]2. Default LLM Configuration[/bold]")
    provider = Prompt.ask(
        "Default model provider",
        choices=["openai", "anthropic", "google_genai", "openrouter"],
        default=str(DEFAULTS["provider"]),
    )
    model = Prompt.ask(
        "Default model name",
        default=MODEL_DEFAULTS.get(provider, str(DEFAULTS["model"])),
    )

    # Async Configuration
    console.print("\n[bold]3. Performance Configuration[/bold]")
    async_enabled = Confirm.ask("Enable async processing?", default=True)
    async_workers = 2
    if async_enabled:
        async_workers = int(
            Prompt.ask(
                "Max async workers",
                default=str(DEFAULTS["async_max_workers"]),
            )
        )

    # API Keys
    console.print("\n[bold]4. API Keys (optional, can add later)[/bold]")
    api_keys: dict[str, str] = {}
    if Confirm.ask("Configure API keys now?", default=False):
        if provider == "openai" or Confirm.ask("Add OpenAI key?", default=False):
            api_keys["OPENAI_API_KEY"] = Prompt.ask("OpenAI API Key", password=True)
        if provider == "anthropic" or Confirm.ask("Add Anthropic key?", default=False):
            api_keys["ANTHROPIC_API_KEY"] = Prompt.ask("Anthropic API Key", password=True)
        if provider == "google_genai" or Confirm.ask("Add Google key?", default=False):
            api_keys["GOOGLE_API_KEY"] = Prompt.ask("Google API Key", password=True)

    _write_defaults_json(working_dir, provider=provider, model=model)
    console.print("\n[green]✓[/green] Created defaults.json")

    _write_env_file(
        working_dir,
        dirs,
        async_enabled=async_enabled,
        async_workers=async_workers,
        api_keys=api_keys,
        header_comment="generated by karenina init --advanced",
    )
    console.print("[green]✓[/green] Created .env")

    console.print("\n[bold green]Advanced setup complete![/bold green]\n")
    return dirs


def init(
    working_dir: Path = typer.Option(
        Path.cwd(),
        "--dir",
        "-d",
        help="Working directory for Karenina data",
    ),
    advanced: bool = typer.Option(
        False,
        "--advanced",
        "-a",
        help="Run advanced setup with all options",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing configuration",
    ),
) -> None:
    """Initialize Karenina configuration and directories.

    Run this to set up a new Karenina workspace or reset an existing one.

    Examples:
        karenina init              # Quick setup with defaults
        karenina init --advanced   # Full guided setup
        karenina init --force      # Reset existing configuration
    """
    defaults_file = working_dir / "defaults.json"

    if defaults_file.exists() and not force:
        console.print("[yellow]Configuration already exists.[/yellow]")
        console.print("Use --force to overwrite, or --advanced to reconfigure.")
        if not Confirm.ask("Overwrite existing configuration?", default=False):
            raise typer.Exit(code=0)

    if advanced:
        run_advanced_setup(working_dir)
    else:
        run_default_setup(working_dir)


def serve(
    port: int = typer.Option(DEFAULT_PORT, "--port", "-p", help="Port to serve on"),
    host: str = typer.Option("localhost", "--host", help="Host to bind to"),
    dev: bool = typer.Option(False, "--dev", help="Run in development mode"),
    working_dir: Path = typer.Option(
        Path.cwd(),
        "--dir",
        "-d",
        help="Working directory for data files",
    ),
    skip_setup: bool = typer.Option(
        False,
        "--skip-setup",
        help="Skip first-time setup",
    ),
) -> None:
    """Start the Karenina webapp server.

    Requires karenina[webapp] to be installed.

    On first run, offers setup options:
    - Default: Quick setup with sensible defaults
    - Advanced: Full guided configuration (use 'karenina init --advanced' first)

    Examples:
        karenina serve                    # Start on localhost:8080
        karenina serve --port 9000        # Custom port
        karenina serve --dir ~/karenina   # Custom working directory
    """
    try:
        from karenina_server.server import (
            find_webapp_directory,
            start_development_server,
            start_fastapi_server,
        )
    except ImportError as e:
        console.print("[red]Error: Webapp dependencies not installed.[/red]")
        console.print("Install with: [cyan]pip install karenina[webapp][/cyan]")
        raise typer.Exit(code=1) from e

    # Check if first-time setup is needed
    defaults_file = working_dir / "defaults.json"
    if not defaults_file.exists() and not skip_setup:
        console.print(
            Panel(
                "Welcome to Karenina! This appears to be a new workspace.",
                title="First Run",
                border_style="blue",
            )
        )
        mode = Prompt.ask(
            "Setup mode",
            choices=["default", "advanced", "skip"],
            default="default",
        )
        if mode == "default":
            run_default_setup(working_dir)
        elif mode == "advanced":
            run_advanced_setup(working_dir)
        # else: skip

    # Set environment variables for this session
    os.environ.setdefault("DB_PATH", str(working_dir / "dbs"))
    os.environ.setdefault("KARENINA_PRESETS_DIR", str(working_dir / "presets"))
    os.environ.setdefault("MCP_PRESETS_DIR", str(working_dir / "mcp_presets"))

    webapp_dir = find_webapp_directory()
    console.print(f"\n[bold]Starting Karenina server on http://{host}:{port}[/bold]\n")

    if dev:
        start_development_server(webapp_dir=webapp_dir, host=host, port=port)
    else:
        start_fastapi_server(webapp_dir=webapp_dir, host=host, port=port)
